# OP-50
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: access-server
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: access-server
